feat: run start vllm server in daemon mode
Signed-off-by: vianho <60379375+vianho@users.noreply.github.com>

diff --git a/prune/jobs/templates/combined_job_sif.pbs.template b/prune/jobs/templates/combined_job_sif.pbs.template
--- a/prune/jobs/templates/combined_job_sif.pbs.template
+++ b/prune/jobs/templates/combined_job_sif.pbs.template
@@ -72,7 +72,7 @@ wait_for_server() {{
     interval=10
     attempt=0
     while ! curl -s "$VLLM_URL/ping"; do
-        if [ $retries -le 0 ]; then echo "Failed to start vLLM server after multiple attempts!"; exit 1; fi
+        if [ $attempt -ge $retries ]; then echo "Failed to start vLLM server after multiple attempts!"; exit 1; fi
         echo "Waiting for vLLM server to start... ($((attempt + 1))/$retries attempts)"
         sleep $interval
         attempt=$((attempt + 1))
